### ISSUE TITLE
Submit element gets label of preview element

### ISSUE THREAD

**Issue by Moongazer** [zendframework/zend-form#61] opened 2016-04-19 12:59 UTC
**zend-form v2.8.0**

If you define a form with elements and a submit button, the submit button gets a label rendered, with the label-name of the last added element.

```
$this->add([
    'name' => 'identity',
    'options' => ['label' => 'eMail'],
    'attributes' => ['type' => 'text'],
]);

$this->add([
    'name' => 'submit',
    'attributes' => [
        'value' => 'Submit Button',
        'type'  => 'submit'
    ],
]);
```

![zend-form-issue](https://cloud.githubusercontent.com/assets/1685510/14639775/9bcd9ea8-063e-11e6-9684-7eb75963638e.PNG)
Unfortunately I could not track down this issue to provide a solution here. A workaround is to provide an options array for the submit-element with an empty label `'options' => ['label' => '']`

**Comment by tflin** [comment] 2016-04-20 01:23
We have the same problem. Not just the submit button. If you have another text input element not setting the label, it will have the previous text input element's label. This does not happen in previous version.

**Comment by jaydiablo** [comment] 2016-04-27 18:35
If this describes the same issue I'm seeing (the "submit" form element receives the text of the previously added element) then it seems that this was introduced in 2.7.1 (if I revert my project to 2.7.0 the input is fixed).

In my case I have a password field defined before a submit field, like so:

```php
$this->add(
            [
                'name'       => 'password',
                'options'    => ['label' => 'Password'],
                'attributes' => [
                    'type'        => 'password',
                    'placeholder' => 'Password',
                ],
            ]
        )->add(
            [
                'name'       => 'submit',
                'attributes' => [
                    'type'  => 'submit',
                    'value' => 'Login',
                    'class' => 'btn',
                ],
            ]
        );
```

In 2.7.1 and up this gets rendered as:

```html
<div class="form-group "><label>Password</label><input name="password" type="password" placeholder="Password" class="form-control" value=""></div>
<div class="form-group "><label>Password</label><button name="submit" type="submit" class="btn&#x20;btn-default" value="Login">Password</button></div>
```

In 2.7.0 it gets rendered as:

```html
<div class="form-group "><label>Password</label><input name="password" type="password" placeholder="Password" class="form-control" value=""></div>
<div class="form-group "><button name="submit" type="submit" class="btn&#x20;btn-default" value="Login">Login</button></div>
```

In 2.8.0 I can fix the issue by providing a label on the Submit element:

```php
$this->add(
            [
                'name'       => 'password',
                'options'    => ['label' => 'Password'],
                'attributes' => [
                    'type'        => 'password',
                    'placeholder' => 'Password',
                ],
            ]
        )->add(
            [
                'name'       => 'submit',
                'options' => ['label' => 'Login'], // Fixes ZF2 form bug
                'attributes' => [
                    'type'  => 'submit',
                    'value' => 'Login',
                    'class' => 'btn',
                ],
            ]
        );
```

Which gives me the proper HTML:

```html
<div class="form-group "><label>Password</label><input name="password" type="password" placeholder="Password" class="form-control" value=""></div>
<div class="form-group "><label>Login</label><button name="submit" type="submit" class="btn&#x20;btn-default" value="Login">Login</button></div>
```

**Comment by weierophinney** [comment] 2016-05-01 19:54
How are you rendering, exactly?

I added a test to the `FormCollection` view helper test suite that:

- creates a form
- adds elements to the form as you note above
- passes the form to the helper's `render()` method
- asserts that the returned markup does not contain the text `<label>Password</label><button name="submit"`

I ran this against both 2.8.1 and current master (which applies a number of fixes around element creation), and it passes against both. As such, my suspicion is that I'm not reproducing the situation exactly.

Can you indicate the steps you took to render the form for me, please?

**Comment by weierophinney** [comment] 2016-05-01 20:25
Also tried adding a test to the `FormRow` view helper test suite that:

- creates a form
- adds elements to the form as noted above
- iterates through the form, aggregating calls to `FormRow::render()` on each element
- asserts the markup does not contain the unexpected label

This test also runs fine against both current master and releases from 2.7.1 forward.

**Comment by weierophinney** [comment] 2016-05-01 20:33
For the final iteration, I used:

```php
$markup = $helper->render($form->get('password'));
$markup .= $helper->render($form->get('submit'));
```

which had the exact same results. At this point, I've exhausted the various possibilities of rendering the elements that are built-in to the component.

**Comment by jaydiablo** [comment] 2016-05-02 03:36
I can't speak for @Moongazer or others, but in my case I'm using this library to render the form:

https://github.com/neilime/zf2-twb-bundle

Which gives me Bootstrap compatible markup.

I just looked through that library's pull requests, and it seems that some changes may have been made that may address this issue, but I haven't tested yet.  That said, changing the version of Zend Form does fix my issue, so perhaps a change in Zend Form has exposed a particular bug that the twb-bundle had.

I'll play with upgrading that library and testing against Zend Form latest with and without that label option.

Thanks for looking into this on your end @weierophinney

**Comment by tflin** [comment] 2016-05-03 02:22
This bug seems to be fixed in zf-form 2.8.2. It still happened on 2.8.1. After upgrading to zf-form 2.8.2, it is OK.

**Comment by jaydiablo** [comment] 2016-05-03 21:05
I can confirm that Zend Form 2.8.3 does not have this issue (if I simply upgrade zend-form and remove that label option my button is once again rendered correctly).

So, based on @tflin's comment, it sounds like this was an issue from 2.7.1 to 2.8.1 (I didn't test 2.8.2 myself).

**Comment by weierophinney** [comment] 2016-05-03 21:08
Thanks for the feedback, everyone! Closing!

**Closed by weierophinney** 2016-05-03 21:08 UTC
Labels: bug, cannot reproduce
